# Generated by Django 4.2.16 on 2024-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='why_choose_us/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='why_choose_us/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='why_choose_us/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Почему выбирают нас',
                'verbose_name_plural': 'Почему выбирают нас?',
                'db_table': 'why_choose_us',
            },
        ),
    ]
