# Generated by Django 4.2.16 on 2024-10-03 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_tgusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+998\\d{9}$')]),
        ),
    ]
