# Generated by Django 4.2.16 on 2024-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_tgusers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusers',
            name='lang',
            field=models.CharField(default='uz', max_length=2),
        ),
        migrations.AddIndex(
            model_name='tgusers',
            index=models.Index(fields=['chat_id'], name='chat_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tgusers',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='tgusers',
            index=models.Index(fields=['phone_number'], name='phone_number_idx'),
        ),
    ]
