# Generated by Django 4.2.16 on 2024-10-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_tgusers_lang_tgusers_chat_id_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faq',
            },
        ),
    ]
