# Generated by Django 4.2.16 on 2024-10-15 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=355, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_price', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'tg_services',
            },
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+998\\d{9}$')]),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.tgservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tgusers')),
            ],
            options={
                'verbose_name': 'Order (Zakaz)',
                'verbose_name_plural': 'Orders (Zakazlar)',
                'db_table': 'orders',
            },
        ),
    ]
