# Generated by Django 4.2.16 on 2024-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_stock_alter_tgservices_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Chegirma', 'verbose_name_plural': 'Chegirmalar'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='tgservices',
            old_name='daily_price',
            new_name='daily_price_ru',
        ),
        migrations.RenameField(
            model_name='tgservices',
            old_name='monthly_price',
            new_name='daily_price_uz',
        ),
        migrations.RenameField(
            model_name='tgservices',
            old_name='size',
            new_name='monthly_price_ru',
        ),
        migrations.RenameField(
            model_name='tgservices',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='stock',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tgservices',
            name='monthly_price_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tgservices',
            name='size_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tgservices',
            name='size_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tgservices',
            name='title_uz',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
