# Generated by Django 4.2.16 on 2024-10-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgservices',
            options={'verbose_name': 'Tg Xizmat', 'verbose_name_plural': 'Tg Xizmatlari'},
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='daily_price_ru',
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='daily_price_uz',
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='monthly_price_ru',
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='monthly_price_uz',
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='size_ru',
        ),
        migrations.RemoveField(
            model_name='tgservices',
            name='size_uz',
        ),
        migrations.CreateModel(
            name='TgServicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_price_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_price_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('size_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_price_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_price_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.tgservices')),
            ],
            options={
                'verbose_name': 'Tg Xizmat Narxi',
                'verbose_name_plural': 'Tg Xizmat Narxlari',
                'db_table': 'tg_services_price',
            },
        ),
    ]
