# Generated by Django 4.2.16 on 2024-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_faq_answer_uz_faq_question_uz_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusers',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
